### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ishanra** [mast-group/codemining-treelm#1]
Hi,

  I could not build this project. I closely followed the procedure you suggested. I am attaching the pom file I used and the corresponding trace.

  Can you please help me to resolve this?

[trace.txt](https://github.com/mast-group/codemining-treelm/files/957440/trace.txt)
[pom (copy).txt](https://github.com/mast-group/codemining-treelm/files/957446/pom.copy.txt)

**Comment by mallamanis** [comment]
Hi, can you please look at [this](https://github.com/mast-group/codemining-sequencelm/issues/1) and let me know if it resolves this issue too?
