### ISSUE TITLE
codemining.java.codeutils.MethodExtractor NOT FOUND in codemining-core

### ISSUE THREAD

**Issue by linzeqipku** [mast-group/codemining-treelm#2]
Hi Miltos,
  
  I want to use this project to mine code idioms, but I encounter a problem:
  
  SampleBlockedTSG uses class java.codeutils.MethodExtractor,
  but I cannot find MethodExtractor in codemining-core.
  Is there something wrong happened?
  I guess maybe it is a version conflict between codemining-core and codemining-treelm?
  
  I'll appreciate it if you can give me some help. Now I'm writting my own MethodExtractor in order to run SampleBlockedTSG...

Best regards,
  Zeqi

**Comment by mallamanis** [comment]
Hi Zeqi,
This seems to be missing from codemining-core. Find the missing file attached.

[MethodExtractor.java.zip](https://github.com/mast-group/codemining-treelm/files/1691769/MethodExtractor.java.zip)

If you find the time, can you submit a PR in codemining-core merging this (unzipped) file? Thanks!
